// ========== i18n TRANSLATIONS ==========
const TRANSLATIONS = {
    en: {
        app_title: "AutoSolve Dashboard",
        app_subtitle: "AI Assistant • Automatic answers",
        settings_title: "Settings",
        theme_label: "Theme",
        language_label: "Language",
        apply_btn: "Apply",
        api_key_label: "🔑 Key",
        api_key_placeholder: "Entre The Key",
        save_key_btn: "💾",
        level_label: "📚 Level",
        save_level_btn: "💾",
        config_loaded: "✅ Configuration loaded",
        config_saved_key: "🔑 API key saved!",
        config_ready: "✅ Configuration ready",
        config_level_selected: "📚 Level {level} selected",
        config_wrong_level: "⚠️ You are on e-devoir-{current} but selected {selected}. Change level or page.",
        config_level_active: "✅ Level {level} active",
        success_stat: "Success",
        errors_stat: "Errors",
        time_stat: "Time",
        progress_label: "📊 Progress",
        status_ready: "✅ System ready",
        status_running: "🟢 Running",
        status_stopped: "⏹️ Stopped by user",
        status_error: "❌ Error",
        status_complete: "🎉 Mission accomplished! {success}/{total} questions solved in {time} seconds",
        status_reset: "✅ Dashboard reset",
        status_waiting_api: "⏳ Waiting for API key...",
        status_analyzing: "🔍 Analyzing question {num}...",
        status_reading_fail: "❌ Cannot read question {num}",
        status_consulting_ai: "🤖 Consulting AI for question {num}...",
        status_answer_received: "✅ Answer received for question {num}",
        status_select_fail: "⚠️ Cannot select answer for question {num}",
        status_error_question: "❌ Error on question {num}: {error}",
        status_nav_error: "⚠️ Navigation problem to question {q}",
        btn_start: "Start",
        btn_stop: "Stop",
        btn_reset: "Reset",
        footer_created: "Created by AMINE HDD",
        footer_control: "Click to control dashboard",
        last_update: "Last update: {time}",
        time_seconds: "{time}s",
        api_missing: "❌ Missing API key. Please add it in the dashboard.",
        api_invalid_response: "Invalid API response",
    },
    fr: {
        app_title: "Tableau de bord AutoSolve",
        app_subtitle: "Assistant IA • Réponse automatique",
        settings_title: "Paramètres",
        theme_label: "Thème",
        language_label: "Langue",
        apply_btn: "Appliquer",
        api_key_label: "🔑 Clé",
        api_key_placeholder: "Entre Le Clé",
        save_key_btn: "💾",
        level_label: "📚 Niveau",
        save_level_btn: "💾",
        config_loaded: "✅ Configuration chargée",
        config_saved_key: "🔑 Clé API enregistrée !",
        config_ready: "✅ Configuration prête",
        config_level_selected: "📚 Niveau {level} sélectionné",
        config_wrong_level: "⚠️ Vous êtes sur e-devoir-{current} mais le niveau sélectionné est {selected}. Changez le niveau ou la page.",
        config_level_active: "✅ Niveau {level} actif",
        success_stat: "Réussies",
        errors_stat: "Échecs",
        time_stat: "Temps",
        progress_label: "📊 Progression",
        status_ready: "✅ Système prêt",
        status_running: "🟢 En cours",
        status_stopped: "⏹️ Arrêté par l'utilisateur",
        status_error: "❌ Erreur",
        status_complete: "🎉 Mission accomplie ! {success}/{total} questions résolues en {time} secondes",
        status_reset: "✅ Tableau de bord réinitialisé",
        status_waiting_api: "⏳ En attente de la clé API...",
        status_analyzing: "🔍 Analyse de la question {num}...",
        status_reading_fail: "❌ Impossible de lire la question {num}",
        status_consulting_ai: "🤖 Consultation de l'IA pour la question {num}...",
        status_answer_received: "✅ Réponse reçue pour la question {num}",
        status_select_fail: "⚠️ Impossible de sélectionner la réponse pour la question {num}",
        status_error_question: "❌ Erreur question {num} : {error}",
        status_nav_error: "⚠️ Problème de navigation vers la question {q}",
        btn_start: "Démarrer",
        btn_stop: "Arrêter",
        btn_reset: "Réinitialiser",
        footer_created: "Created by AMINE HDD",
        footer_control: "Cliquez pour contrôler le tableau de bord",
        last_update: "Dernière mise à jour : {time}",
        time_seconds: "{time}s",
        api_missing: "❌ Clé API manquante. Veuillez l'ajouter dans le tableau de bord.",
        api_invalid_response: "Réponse invalide de l'API",
    },
    ar: {
        app_title: "لوحة التحكم AutoSolve",
        app_subtitle: "مساعد الذكاء الاصطناعي • إجابات تلقائية",
        settings_title: "الإعدادات",
        theme_label: "المظهر",
        language_label: "اللغة",
        apply_btn: "تطبيق",
        api_key_label: "🔑 المفتاح",
        api_key_placeholder: "أدخل المفتاح",
        save_key_btn: "💾",
        level_label: "📚 المستوى",
        save_level_btn: "💾",
        config_loaded: "✅ تم تحميل الإعدادات",
        config_saved_key: "🔑 تم حفظ مفتاح API!",
        config_ready: "✅ الإعدادات جاهزة",
        config_level_selected: "📚 تم اختيار المستوى {level}",
        config_wrong_level: "⚠️ أنت على e-devoir-{current} ولكن المستوى المختار هو {selected}. غير المستوى أو الصفحة.",
        config_level_active: "✅ المستوى {level} نشط",
        success_stat: "ناجحة",
        errors_stat: "أخطاء",
        time_stat: "الوقت",
        progress_label: "📊 التقدم",
        status_ready: "✅ النظام جاهز",
        status_running: "🟢 قيد التشغيل",
        status_stopped: "⏹️ تم الإيقاف بواسطة المستخدم",
        status_error: "❌ خطأ",
        status_complete: "🎉 تم المهمة! {success}/{total} سؤال تم حلها في {time} ثانية",
        status_reset: "✅ تم إعادة تعيين لوحة التحكم",
        status_waiting_api: "⏳ في انتظار مفتاح API...",
        status_analyzing: "🔍 تحليل السؤال {num}...",
        status_reading_fail: "❌ لا يمكن قراءة السؤال {num}",
        status_consulting_ai: "🤖 استشارة الذكاء الاصطناعي للسؤال {num}...",
        status_answer_received: "✅ تم استلام الإجابة للسؤال {num}",
        status_select_fail: "⚠️ لا يمكن تحديد الإجابة للسؤال {num}",
        status_error_question: "❌ خطأ في السؤال {num}: {error}",
        status_nav_error: "⚠️ مشكلة في التنقل إلى السؤال {q}",
        btn_start: "ابدأ",
        btn_stop: "إيقاف",
        btn_reset: "إعادة تعيين",
        footer_created: "Created by AMINE HDD",
        footer_control: "انقر للتحكم في لوحة التحكم",
        last_update: "آخر تحديث: {time}",
        time_seconds: "{time}ث",
        api_missing: "❌ مفتاح API مفقود. يرجى إضافته في لوحة التحكم.",
        api_invalid_response: "استجابة API غير صالحة",
    }
};

// ========== PREMIUM THEME DEFINITIONS ==========
const themes = {
    blue: {
        '--bg-primary': 'linear-gradient(135deg, #0a0e17 0%, #1a1a2e 50%, #16213e 100%)',
        '--bg-solid': '#0f172a',
        '--bg-glass': '#1e293b',
        '--bg-glass-hover': '#2d3a4f',
        '--border-glass': 'rgba(100, 120, 180, 0.25)',
        '--neon-blue': '#0099FF',
        '--neon-green': '#00ff9d',
        '--neon-purple': '#b76eff',
        '--neon-red': '#ff4d6a',
        '--text-primary': '#f0f4ff',
        '--text-secondary': '#a8b3cf',
        '--text-muted': '#6b7594',
        '--shadow-soft': '0 8px 32px rgba(0, 0, 0, 0.35)',
        '--shadow-glow-blue': '0 0 20px rgba(0, 153, 255, 0.4)',
        '--shadow-glow-green': '0 0 20px rgba(0, 255, 157, 0.4)',
        '--shadow-glow-red': '0 0 20px rgba(255, 77, 106, 0.4)',
        '--shadow-glow-purple': '0 0 25px rgba(183, 110, 255, 0.35)',
        '--radius-sm': '12px',
        '--radius-md': '16px',
        '--radius-lg': '20px',
        '--radius-full': '9999px',
        '--transition-fast': '0.2s ease',
        '--transition-normal': '0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        '--transition-slow': '0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        '--progress-fill': 'linear-gradient(90deg, #0099FF, #b76eff)',
        '--stat-value': '#0099FF'
    },
    red: {
        '--bg-primary': 'linear-gradient(135deg, #2d1a1a 0%, #1a0f0f 100%)',
        '--bg-solid': '#2c1a1a',
        '--bg-glass': '#3a2626',
        '--bg-glass-hover': '#4d3535',
        '--border-glass': 'rgba(239, 68, 68, 0.25)',
        '--neon-blue': '#ff6b6b',
        '--neon-green': '#ff8e8e',
        '--neon-purple': '#ff4d6a',
        '--neon-red': '#ff4d6a',
        '--text-primary': '#ffe0e0',
        '--text-secondary': '#ffb3b3',
        '--text-muted': '#cc8888',
        '--shadow-soft': '0 8px 32px rgba(0, 0, 0, 0.35)',
        '--shadow-glow-blue': '0 0 20px rgba(255, 107, 107, 0.4)',
        '--shadow-glow-green': '0 0 20px rgba(255, 142, 142, 0.4)',
        '--shadow-glow-red': '0 0 20px rgba(255, 77, 106, 0.4)',
        '--shadow-glow-purple': '0 0 25px rgba(255, 77, 106, 0.35)',
        '--radius-sm': '12px',
        '--radius-md': '16px',
        '--radius-lg': '20px',
        '--radius-full': '9999px',
        '--transition-fast': '0.2s ease',
        '--transition-normal': '0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        '--transition-slow': '0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        '--progress-fill': 'linear-gradient(90deg, #ef4444, #dc2626)',
        '--stat-value': '#ef4444'
    },
    green: {
        '--bg-primary': 'linear-gradient(135deg, #1a2d1a 0%, #0f1a0f 100%)',
        '--bg-solid': '#1a2e1a',
        '--bg-glass': '#2a452a',
        '--bg-glass-hover': '#3a5e3a',
        '--border-glass': 'rgba(16, 185, 129, 0.25)',
        '--neon-blue': '#10b981',
        '--neon-green': '#00ff9d',
        '--neon-purple': '#34d399',
        '--neon-red': '#ff6b6b',
        '--text-primary': '#e0ffe0',
        '--text-secondary': '#b3ffb3',
        '--text-muted': '#88cc88',
        '--shadow-soft': '0 8px 32px rgba(0, 0, 0, 0.35)',
        '--shadow-glow-blue': '0 0 20px rgba(16, 185, 129, 0.4)',
        '--shadow-glow-green': '0 0 20px rgba(0, 255, 157, 0.4)',
        '--shadow-glow-red': '0 0 20px rgba(255, 107, 107, 0.4)',
        '--shadow-glow-purple': '0 0 25px rgba(52, 211, 153, 0.35)',
        '--radius-sm': '12px',
        '--radius-md': '16px',
        '--radius-lg': '20px',
        '--radius-full': '9999px',
        '--transition-fast': '0.2s ease',
        '--transition-normal': '0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        '--transition-slow': '0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        '--progress-fill': 'linear-gradient(90deg, #10b981, #059669)',
        '--stat-value': '#10b981'
    },
    purple: {
        '--bg-primary': 'linear-gradient(135deg, #2d1a3a 0%, #1a0f2a 100%)',
        '--bg-solid': '#2a1a3a',
        '--bg-glass': '#3d2a52',
        '--bg-glass-hover': '#513a6b',
        '--border-glass': 'rgba(139, 92, 246, 0.25)',
        '--neon-blue': '#8b5cf6',
        '--neon-green': '#a78bfa',
        '--neon-purple': '#b76eff',
        '--neon-red': '#ff6b6b',
        '--text-primary': '#f0e0ff',
        '--text-secondary': '#d4b3ff',
        '--text-muted': '#aa88cc',
        '--shadow-soft': '0 8px 32px rgba(0, 0, 0, 0.35)',
        '--shadow-glow-blue': '0 0 20px rgba(139, 92, 246, 0.4)',
        '--shadow-glow-green': '0 0 20px rgba(167, 139, 250, 0.4)',
        '--shadow-glow-red': '0 0 20px rgba(255, 107, 107, 0.4)',
        '--shadow-glow-purple': '0 0 25px rgba(183, 110, 255, 0.35)',
        '--radius-sm': '12px',
        '--radius-md': '16px',
        '--radius-lg': '20px',
        '--radius-full': '9999px',
        '--transition-fast': '0.2s ease',
        '--transition-normal': '0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        '--transition-slow': '0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        '--progress-fill': 'linear-gradient(90deg, #8b5cf6, #7c3aed)',
        '--stat-value': '#8b5cf6'
    },
    white: {
        '--bg-primary': 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
        '--bg-solid': '#f1f5f9',
        '--bg-glass': '#ffffff',
        '--bg-glass-hover': '#f8fafc',
        '--border-glass': 'rgba(0, 0, 0, 0.1)',
        '--neon-blue': '#3b82f6',
        '--neon-green': '#10b981',
        '--neon-purple': '#8b5cf6',
        '--neon-red': '#ef4444',
        '--text-primary': '#0f172a',
        '--text-secondary': '#475569',
        '--text-muted': '#64748b',
        '--shadow-soft': '0 8px 32px rgba(0, 0, 0, 0.15)',
        '--shadow-glow-blue': '0 0 20px rgba(59, 130, 246, 0.3)',
        '--shadow-glow-green': '0 0 20px rgba(16, 185, 129, 0.3)',
        '--shadow-glow-red': '0 0 20px rgba(239, 68, 68, 0.3)',
        '--shadow-glow-purple': '0 0 25px rgba(139, 92, 246, 0.25)',
        '--radius-sm': '12px',
        '--radius-md': '16px',
        '--radius-lg': '20px',
        '--radius-full': '9999px',
        '--transition-fast': '0.2s ease',
        '--transition-normal': '0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        '--transition-slow': '0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        '--progress-fill': 'linear-gradient(90deg, #3b82f6, #2563eb)',
        '--stat-value': '#3b82f6'
    },
    dark: {
        '--bg-primary': 'linear-gradient(135deg, #0a0a0a 0%, #000000 100%)',
        '--bg-solid': '#0a0a0a',
        '--bg-glass': '#1a1a1a',
        '--bg-glass-hover': '#2a2a2a',
        '--border-glass': 'rgba(255, 255, 255, 0.1)',
        '--neon-blue': '#64748b',
        '--neon-green': '#94a3b8',
        '--neon-purple': '#a3a3a3',
        '--neon-red': '#737373',
        '--text-primary': '#e5e5e5',
        '--text-secondary': '#a3a3a3',
        '--text-muted': '#737373',
        '--shadow-soft': '0 8px 32px rgba(0, 0, 0, 0.5)',
        '--shadow-glow-blue': '0 0 20px rgba(100, 116, 139, 0.3)',
        '--shadow-glow-green': '0 0 20px rgba(148, 163, 184, 0.3)',
        '--shadow-glow-red': '0 0 20px rgba(115, 115, 115, 0.3)',
        '--shadow-glow-purple': '0 0 25px rgba(163, 163, 163, 0.25)',
        '--radius-sm': '12px',
        '--radius-md': '16px',
        '--radius-lg': '20px',
        '--radius-full': '9999px',
        '--transition-fast': '0.2s ease',
        '--transition-normal': '0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        '--transition-slow': '0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        '--progress-fill': 'linear-gradient(90deg, #525252, #404040)',
        '--stat-value': '#a3a3a3'
    }
};

const TOTAL_QUESTIONS = 20;